--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/lovetwice1012/MyWarp-en
build-by-default: true
branches:
- master
projects:
  mywarp-en:
    path: mywarp-en/
    icon: E83B2EE0-6877-40E5-B26B-00A9A2F49452.png
...
