--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/lovetwice1012/MyWarp-en
build-by-default: true
branches:
- master
projects:
  mywarp-en:
    path: ./
    icon: 744A0886-447F-4D37-9A7F-4CFA8ACE3736.png
...
