name: MyWarp
version: 1.0.0
author: lovetwice1012
api: 3.0.0
main: MyWarp\MyWarp
description: Players can save their own warp points
commands:
    mywarp:
        description: Manage your own warp points.
        usage: /mywarp
    myw:
        description: Manage your own warp points.
        usage: /myw