name: MyWarp
version: 1.1.0
author: lovetwice1012
api: 3.0.0
main: lovetwice1012\MyWarp\MyWarp
description: Players can save their own warp points
commands:
    mywarp:
        description: Manage your own warp points.
        usage: /mywarp
    myw:
        description: Manage your own warp points.
        usage: /myw
 
permissions:
   lovetwice1012.mywarp.*:
     description: Players can manage their own warp points
     children:
       mywarp.mywarp: true
       mywarp.myw: true
       mywarp.add: true
       mywarp.delete: true
       mywarp.warp: true
   mywarp.mywarp:
     description: Players can use mywarp command to manage their own warp points
     default: true
   mywarp.myw:
     description: Players can use mywarp command to manage their own warp points
     default: true
   mywarp.add:
     description: Players can add their own warp points
     default: true
   mywarp.delete:
     description: Players can delete their own warp points
     default: true
   mywarp.warp:
     description: Players can warp their own warp points
     default: true
